
# -----------------------------------------------------------------------------
# Alias

# Need to provide he following alias:
# /control/alias ACTIVITY_BQ 10

/control/execute mac/alias_2.mac
/control/execute mac/nm670/alias_rad_colli.mac

# -----------------------------------------------------------------------------
# Geometry definition

#/control/execute mac/visu.mac

/control/execute mac/verbose.mac
/control/execute mac/world.mac
/control/execute mac/phantom_ct.mac
/control/execute mac/nm670/spect.mac
/control/execute mac/spect_detector_input_plane.mac

# One single head
/control/execute mac/nm670/spect_translation.mac
/control/execute mac/nm670/spect_rotation.mac


# -----------------------------------------------------------------------------
# Physics

/control/execute mac/physics_list.mac
/control/execute mac/physics_cuts_phantom.mac
/control/execute mac/physics_cuts_spect_head.mac

# -----------------------------------------------------------------------------
# OUTPUT

/control/execute mac/output_stat.mac
/control/execute mac/nm670/output_projections_{RADIONUCLIDE}.mac

# -----------------------------------------------------------------------------
# INITIALISATION

/gate/run/initialize

# -----------------------------------------------------------------------------
# SOURCE

/control/execute mac/source_vox.mac


# -----------------------------------------------------------------------------
# START

/control/listAlias
/control/execute mac/start_time.mac



