

/gate/physics/addPhysicsList emstandard_opt4
# alternative: opt2 opt3 opt4 (slowest + most accurate)

# add the following line if source is decaying ion (no need if gamma source)
#/gate/physics/addProcess RadioactiveDecay

# High cuts by default, to be decrease in phantom and spect head
/gate/physics/Gamma/SetCutInRegion      world 1 km
/gate/physics/Electron/SetCutInRegion   world 1 km
/gate/physics/Positron/SetCutInRegion   world 1 km


