

/control/alias SOURCE_GAMMA_SPECTRUM_FILE data/nm670/energy_spectrum_{RADIONUCLIDE}.txt

/gate/source/addSource RadionuclideSource voxel
/gate/source/RadionuclideSource/attachTo phantom
/gate/source/RadionuclideSource/reader/insert image
/gate/source/RadionuclideSource/imageReader/translator/insert linear
/gate/source/RadionuclideSource/imageReader/linearTranslator/setScale {GAMMA_ACTIVITY_BQ} Bq
/gate/source/RadionuclideSource/imageReader/readFile {SOURCE_IMAGE} 
/gate/source/RadionuclideSource/TranslateTheSourceAtThisIsoCenter {SOURCE_ISOCENTER_X} {SOURCE_ISOCENTER_Y} {SOURCE_ISOCENTER_Z} mm

# WARNING
# the source is attached to the phantom
# the "iscenter" for the source is thus the center of the bounding box of the CT

# Note the here, the ct phantom is rotated, so we need to attach the source so that it rotates also

/gate/source/RadionuclideSource/gps/angtype iso
/gate/source/RadionuclideSource/gps/particle gamma
/gate/source/RadionuclideSource/gps/angtype iso
/gate/source/RadionuclideSource/gps/energytype UserSpectrum
/gate/source/RadionuclideSource/gps/setSpectrumFile {SOURCE_GAMMA_SPECTRUM_FILE}
/gate/source/RadionuclideSource/setForcedHalfLife {RADIONUCLIDE_HALF_LIFE_SEC} s


